services:
  nginx:
    image: angelo/nginx:development
    restart: on-failure
    container_name: angel-nginx
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    # volumes:
    #   - tls_certs:/etc/nginx/certs

volumes:
  tls_certs: