ARG BASE_IMAGE=angelo/nginx

#####################################
# Includes self-signed certificates #
#####################################
FROM ${BASE_IMAGE} AS development

WORKDIR /etc/nginx/certs

USER root
RUN apk add openssl

COPY src/defaults/openssl.conf openssl.conf

# --- ECDSA CERT (prime256v1) ---
RUN [ -f ecdsa.crt ] || ( \
    openssl ecparam -name prime256v1 -genkey -noout -out ecdsa.key && \
    openssl req -new -key ecdsa.key -out ecdsa.csr -config openssl.conf && \
    openssl req -new -x509 -in ecdsa.csr -key ecdsa.key \
        -out ecdsa.crt \
        -days 365 \
        -config openssl.conf -extensions v3_req\
)

# --- RSA (4096-bit) ---
RUN [ -f rsa.crt ] || ( \
    openssl req -newkey rsa:4096 -nodes -keyout rsa.key -out rsa.csr -config openssl.conf && \
    openssl x509 -req -in rsa.csr -signkey rsa.key -out rsa.crt -days 365 -extfile openssl.conf -extensions v3_req \
)

# Root CA
RUN cp ecdsa.crt ca.pem

# Clean up
RUN apk del openssl
WORKDIR /etc/nginx

COPY src/defaults/nginx.conf nginx.conf
COPY src/defaults/conf.d conf.d

# Permissions
RUN chown -R nginx:nginx /etc/nginx/certs
RUN chmod 600 /etc/nginx/certs/*
USER nginx

# ENTRYPOINT [ "tail", "-f", "/dev/null" ]