name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}
    env:
      MAJOR_VERSION: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # TODO: Use only actions or CLI, not both
      # - name: Build base image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: src/Dockerfile
      #     push: false
      #     tags: "angelo/nginx"
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      #     load: true

      - name: Build image
        run: make ci

      - name: Update version tag
        id: set-tag
        run: echo "tag=${MAJOR_VERSION}.${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Push image
        run: |
          docker tag angelo/nginx:latest ${{ secrets.DOCKERHUB_USER }}/nginx:${{ steps.set-tag.outputs.tag }}
          docker tag angelo/nginx:latest ${{ secrets.DOCKERHUB_USER }}/nginx:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/nginx:${{ steps.set-tag.outputs.tag }}
          docker push ${{ secrets.DOCKERHUB_USER }}/nginx:latest