name: Build & Publish Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build dev image
        run: make dev

      - run: docker save nginx:${GITHUB_SHA::7} -o image.tar

      - uses: actions/upload-artifact@v3
        with:
          name: nginx-latest
          path: image.tar

    push:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: nginx-latest

        - run: docker load -i image.tar

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Tag and push image
          run: |
            docker tag nginx:${GITHUB_SHA::7} ${{ secrets.DOCKERHUB_USER }}/nginx:${GITHUB_SHA::7}
            docker push ${{ secrets.DOCKERHUB_USER }}/nginx:${GITHUB_SHA::7}
