name: CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Dockerfile
          push: false
          tags: "angelo/nginx"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Build final image
        run: make ci

      - name: Tag and push image
        run: |
          docker tag angelo/nginx:latest ${{ secrets.DOCKERHUB_USER }}/nginx:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKERHUB_USER }}/nginx:${GITHUB_SHA::7}