name: Build & Publish Image

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Install build tools
      #   run: sudo apt-get update && sudo apt-get install -y make

      # - name: Build Docker image
      #   run: make build

      # - name: Set output tag
      #   id: set-tag
      #   run: echo "tag=nginx:latest" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Tag and push image
      #   run: |
      #     docker tag angelo/nginx:development ${{ secrets.DOCKERHUB_USER }}/nginx:latest
      #     docker push ${{ secrets.DOCKERHUB_USER }}/nginx:latest

      - name: Build base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Dockerfile
          push: false
          tags: "angelo/nginx:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/Dockerfile.dev
          push: true
          tags: "${{ secrets.DOCKERHUB_USER }}/nginx:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max